import { Eater  } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { MusicProvider } from '@/styles/MusicContext';

const eater = Eater({
  weight: '400',               // 👈 ESTO ES LO QUE ARREGLA EL ERROR
  subsets: ['latin'],
  variable: '--font-eater',    // Tu variable inventada perfecta
  display: 'swap',
})

const locales = ['es', 'en', 'fr', 'de'];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!locales.includes(locale)) {
    notFound();
  }
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body className ={`${eater.variable}`}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <MusicProvider>
          {children}
          </MusicProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
