import { DM_Mono, Geist_Mono, Cascadia_Mono , Fragment_Mono, Cutive_Mono, Inter  } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { MusicProvider } from '@/styles/MusicContext';


const locales = ['es', 'en', 'fr', 'de'];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!locales.includes(locale)) {
    notFound();
  }
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body >
        <NextIntlClientProvider messages={messages} locale={locale}>
          <MusicProvider>
          {children}
          </MusicProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
